# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Tests [develop]

on:
  pull_request:
    branches: [ develop ]

  push:
    branches: [ develop ]

jobs:

  quality:
    name: Code QA
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install black flake8 isort
    - run: black --version
    - run: isort --check .
    - run: black --check .
    - run: flake8 .

  tests:
    name: Unit tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    needs: quality
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python setup.py develop
    - run: pip install -r tests/requirements.txt
    - name: Print environment
      run: |
        pip freeze
        env | sort
    - name: Run tests
      run: pytest
    - name: Generate Coverage
      run: |
        pip install coverage
        coverage run -m pytest
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true


